# Project: 0925-4
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = practice4.o
LINKOBJ  = practice4.o
LIBS     = -L"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/lib" -L"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/include" -I"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/include" -I"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/1PROGRAMMING/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 0925-4.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\1PROGRAMMING\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

practice4.o: practice4.c
	$(CC) -c practice4.c -o practice4.o $(CFLAGS)
